### PR TITLE
#28 - clear all button to reset advanced search field to default values

### PR DESCRIPTION
**Pull request by edmundchan8**
#28 - Input button placed next to search button on advanced search page.  Javascript code added to database_base.js file that targets the #id tag - advanced-form, calling the reset() function on it, which resets the entire form to their default values.

### CODE REVIEW

**Comment by Enhaloed** [comment]
image
I had tried this previously but the reset breaks all of the third party dropdowns that we use. I hadn't found an obvious fix to this yet and was considering replacing them.

**Comment by edmundchan8** [comment]
@Enhaloed Ah ha, interesting, did not notice that, will have a rethink

**Comment by edmundchan8** [comment]
@Enhaloed Yeah, this is tricky.  I played around with targeting all the input element tags only and resetting those, but that affects other input tags.  

The other thing I was thinking was to have a specific class for only the element you wanted to reset.  But otherwise, I feel like a hard coded way to fix this would work temporarily (until a better solution came along)

Going to stop working on this for the time being.

**Comment by Kossetsoup** [comment]
Closing for now, feel free to reopen when any more changes are made (last response makes me feel like it's not finished?)

**Comment by edmundchan8** [comment]
@Kossetsoup You are correct, I never finished this, apologies.  I had an idea on how to get it to work but it would require a little bit of work.  Definitely close this for now, or maybe someone else can start afresh on this

**Comment by Kossetsoup** [comment]
@edmundchan8 No need for an apology, all good!

**Pull request closed without merging**
