### PR TITLE
Aggregate costs symbols >5 in 6+ Button #17

### PR DESCRIPTION
**Pull request by Zaloog**
Added a "6+" Button for total costs [6, 7, 8, 9, 10 , 11, 12]

### CODE REVIEW

**Comment by Enhaloed** [comment]
As discussed - best to find a way to still be able to search for individual costs. 

Perhaps a "more" or ">>" or "+ or similar button that on press will expand to show 6-12 individually

Happy to help with js/html if needed just @ me

**Comment by Zaloog** [comment]
Despite the fact, that you argued to still have individual selection, there are only ~100 cards falling under the "6+"
category, 60 of those have cost 6. 
I dont think anyone needs that much granularity when searching in 2,5% of the actual database. Or <1% for a "7+" button.

I personally find it easier to just have those aggregated in a "6/7+"-Button for searching. Maybe we can do some kind of poll, to see what the users are more happy with?

**Comment by Kossetsoup** [comment]
I propose a combination of the two options presented.

By default the display will have the numbers as proposed by @Zaloog: 1, up to 6+. Then we can include a button at the end with a ">" or "..." as @Enhaloed suggested which will expand the buttons available. This way the granularity is available to people who want it, but will not clutter the screen for the most general use cases.

**Comment by Kossetsoup** [comment]
Closing this PR as stale, went with a scrolling solution for the costs on mobile. Sorry for the delay in actioning this.

**Pull request closed without merging**
