### PR TITLE
Add dark mode theme #62

### PR DESCRIPTION
**Pull request by Niebvelungen**
This implements a dark theme + toggle for ForceOfWind
Base Dark theme is achieved by loading bootstrap darkmode and adjusting certain styles via a override css.
Toggle sets a cookie and cookie will be read on site load via request cookies.
Can be hot toggles since dark and light mode are loaded on load but disabled in dom.

### CODE REVIEW

**Comment by Niebvelungen** [comment]
I also fixed a little bug on deck editing on mobile where the cost on advanced search bugged out.
image
image

**Comment by Niebvelungen** [comment]
@Enhaloed @Kossetsoup PR is ready to be reviewed

**Comment by Kossetsoup** [comment]
It's looking good! Just one thing to consider changing here:

image
In a card search: the paginated selector doesn't seem to highlight the selected choice, other than by changing the text but I don't feel it's very readable (in comparison to the light version, which highlights it red). Maybe make it purple to match the colour you've chosen for the header?

That's all that stood out to me, so if you could change that I'd be happy to merge it! Appreciate the fix to the total cost slider as well!

**Comment by Niebvelungen** [comment]
> It's looking good! Just one thing to consider changing here:
> 
> image In a card search: the paginated selector doesn't seem to highlight the selected choice, other than by changing the text but I don't feel it's very readable (in comparison to the light version, which highlights it red). Maybe make it purple to match the colour you've chosen for the header?
> 
> That's all that stood out to me, so if you could change that I'd be happy to merge it! Appreciate the fix to the total cost slider as well!

image

Fixed it with the latest commit

**Review by Kossetsoup — APPROVED** [review]
Looks good, happy to merge!

**Pull request merged**
